# Generated by Django 4.2.17 on 2025-08-22 13:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionProxy",
            fields=[],
            options={
                "verbose_name": "Permission Overview",
                "verbose_name_plural": "Permissions Overview",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.permission",),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
