# Generated by Django 4.2.17 on 2025-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Brand Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Feature Name')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Number')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Model Name')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='BHD', max_length=10, verbose_name='Currency')),
                ('body_type', models.CharField(max_length=100, verbose_name='Body type')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage (KM)')),
                ('engine_type', models.CharField(
                    choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'),
                             ('hybrid', 'Hybrid')], max_length=50, verbose_name='Engine Type')),
                ('engine_capacity',
                 models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Engine Capacity (L)')),
                ('cylinders', models.PositiveSmallIntegerField(verbose_name='Cylinders')),
                ('transmission', models.CharField(
                    choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'),
                             ('dual_clutch', 'Dual Clutch')], max_length=20, verbose_name='Transmission')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Number of Seats')),
                ('condition',
                 models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-owned')],
                                  max_length=20, verbose_name='Condition')),
                ('condition_ar', models.CharField(max_length=20, verbose_name='Arabic Condition')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Negotiable')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles',
                                            to='vehicles.brand')),
                ('features', models.ManyToManyField(blank=True, related_name='vehicles', to='vehicles.feature')),
                ('inquiry_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='vehicles', to='vehicles.inquirydata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type Name')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                              to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
