# Generated by Django 4.2.17 on 2025-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='for_rent',
            field=models.BooleanField(default=False, verbose_name='For Rent'),
        ),
    ]
