# Generated by Django 4.2.17 on 2025-07-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_vehicle_is_negotiable"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="primary",
            field=models.BooleanField(default=True, verbose_name="Primary Brand"),
        ),
    ]
