# Generated by Django 4.2.17 on 2025-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0002_vehicle_for_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='condition_ar',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='for_rent',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contract_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('rent_to_own', 'Rent to Own')],
                                   default='rent', max_length=20, verbose_name='Contract Type'),
        ),
    ]
