# Generated by Django 4.2.17 on 2025-06-01 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_remove_vehicle_condition_ar_remove_vehicle_for_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vehicles',
                                   to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(related_name='favorited_by', to='vehicles.vehicle')),
            ],
        ),
    ]
