# Generated by Django 4.2.17 on 2025-06-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0004_favoritevehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='favorite_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
