# Generated by Django 4.2.17 on 2025-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0006_brand_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="staff_only",
            field=models.BooleanField(default=False),
        ),
    ]
