# Generated by Django 4.2.17 on 2025-07-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0007_vehicle_staff_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("vehicle", "start_date")},
            },
        ),
    ]
