# Generated by Django 4.2.17 on 2025-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0008_vehicleprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Available"),
        ),
    ]
