# Generated by Django 4.2.17 on 2025-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0009_vehicle_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="available_units",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of identical vehicles available for rent.",
                verbose_name="Available Units",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_gt_3mo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Price > 3 Months",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_lt_month",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Price < 1 Month",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_month",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Price / Month",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_negotiable",
            field=models.BooleanField(default=False, verbose_name="السعر قابل للتفاوض"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
