# Generated by Django 4.2.17 on 2025-07-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0010_vehicle_available_units_vehicle_price_gt_3mo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price_gt_3mo',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_lt_month',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_month',
        ),
        migrations.CreateModel(
            name='VehiclePriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveIntegerField(help_text='Minimum number of days for this price tier')),
                ('max_days',
                 models.PositiveIntegerField(blank=True, help_text='Leave blank for no upper limit', null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers',
                                              to='vehicles.vehicle')),
            ],
        ),
    ]
