# Generated by Django 4.2.17 on 2025-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0010_vehicle_available_units_vehicle_price_gt_3mo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("rent_to_own", "Rent to Own"),
                    ("rent", "Rent"),
                ],
                default="used",
                max_length=20,
                verbose_name="Vehicle Type",
            ),
        ),
    ]
