# Generated by Django 4.2.17 on 2025-07-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_remove_vehicle_condition_and_more'),
        ('vehicles', '0011_remove_vehicle_price_gt_3mo_and_more'),
    ]

    operations = [
    ]
