# Generated by Django 4.2.17 on 2025-05-14 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0002_vehicle_for_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('license_front_photo', models.ImageField(upload_to='licenses/front/')),
                ('license_back_photo', models.ImageField(upload_to='licenses/back/')),
                ('id_front_photo', models.ImageField(upload_to='ids/front/')),
                ('id_back_photo', models.ImageField(upload_to='ids/back/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'),
                             ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending',
                    max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals',
                                                    to='rental.customerdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rentals',
                                           to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals',
                                              to='vehicles.vehicle')),
            ],
        ),
    ]
