# Generated by Django 4.2.17 on 2025-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
    ]
