# Generated by Django 4.2.17 on 2025-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rental', '0002_alter_customerdata_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
