# Generated by Django 4.2.17 on 2025-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0003_customerdata_middle_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="inspection_form",
            field=models.FileField(blank=True, null=True, upload_to="inspections/"),
        ),
    ]
