# Generated by Django 4.2.17 on 2025-07-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0004_rental_inspection_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="customer_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentals",
                to="rental.customerdata",
            ),
        ),
    ]
