# Generated by Django 4.2.17 on 2025-05-13 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('comfort_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Comfort Rating')),
                ('interior_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Interior Rating')),
                ('exterior_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Exterior Rating')),
                ('price_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Price Rating')),
                ('performance_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Performance Rating')),
                ('reliability_rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)], verbose_name='Reliability Rating')),
                ('save_info',
                 models.BooleanField(default=False, help_text='Save name, email, and website for next time',
                                     verbose_name='Save user info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                              to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Review',
                'verbose_name_plural': 'Vehicle Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
