# Generated by Django 4.2.17 on 2025-05-13 22:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours_start', models.TimeField(verbose_name='Working Hours Start')),
                ('working_hours_end', models.TimeField(verbose_name='Working Hours End')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('max_bookings', models.PositiveSmallIntegerField(default=1, verbose_name='Maximum Bookings')),
                ('current_bookings', models.PositiveSmallIntegerField(default=0, verbose_name='Current Bookings')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots',
                                               to='services.servicelocation')),
            ],
            options={
                'verbose_name': 'Service Time Slot',
                'verbose_name_plural': 'Service Time Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('location', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='UpholsteryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upholstery/materials/',
                                            verbose_name='Material Image')),
                ('price_per_seat', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price per Seat')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('durability_rating',
                 models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                                                  help_text='Rating from 1 (least durable) to 5 (most durable)',
                                                  validators=[django.core.validators.MinValueValidator(1)],
                                                  verbose_name='Durability Rating')),
            ],
            options={
                'verbose_name': 'Upholstery Material',
                'verbose_name_plural': 'Upholstery Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UpholsteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Base Price')),
                ('estimated_hours', models.PositiveSmallIntegerField(default=4, verbose_name='Estimated Hours')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Upholstery Type',
                'verbose_name_plural': 'Upholstery Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UpholsteryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upholstery/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('vehicle_info', models.CharField(blank=True, max_length=255, verbose_name='Vehicle Information')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images',
                                   to='services.upholsterymaterial')),
                ('upholstery_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images',
                                   to='services.upholsterytype')),
            ],
            options={
                'verbose_name': 'Upholstery Gallery Image',
                'verbose_name_plural': 'Upholstery Gallery Images',
                'ordering': ['-featured', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UpholsteryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Seats')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'),
                             ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20,
                    verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Total Price')),
                ('deposit_paid',
                 models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Deposit Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Special Requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion Time')),
                ('accent_material',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   related_name='accent_bookings', to='services.upholsterymaterial')),
                ('primary_material',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_bookings',
                                   to='services.upholsterymaterial')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings',
                                                to='services.servicetimeslot')),
                ('upholstery_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings',
                                   to='services.upholsterytype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='upholstery_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upholstery Booking',
                'verbose_name_plural': 'Upholstery Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upholstery/bookings/', verbose_name='Image')),
                ('is_before', models.BooleanField(default=True, verbose_name='Before Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                              to='services.upholsterybooking')),
            ],
            options={
                'verbose_name': 'Booking Image',
                'verbose_name_plural': 'Booking Images',
                'ordering': ['is_before', 'id'],
            },
        ),
    ]
