# Generated by Django 4.2.17 on 2025-05-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpholsteryCarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Car Model Name')),
            ],
            options={
                'verbose_name': 'Upholstery Car Model',
                'verbose_name_plural': 'Upholstery Car Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UpholsteryMaterialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material Type Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upholstery/material_types/',
                                            verbose_name='Material Type Image')),
            ],
            options={
                'verbose_name': 'Upholstery Material Type',
                'verbose_name_plural': 'Upholstery Material Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='upholsterybooking',
            options={'verbose_name': 'Upholstery Booking', 'verbose_name_plural': 'Upholstery Bookings'},
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='accent_material',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='upholsterybooking',
            name='upholstery_type',
        ),
        migrations.AlterField(
            model_name='upholsterybooking',
            name='primary_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='primary_bookings', to='services.upholsterymaterial'),
        ),
        migrations.AddField(
            model_name='upholsterybooking',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='model_bookings', to='services.upholsterycarmodels'),
        ),
        migrations.AddField(
            model_name='upholsterybooking',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='material_bookings', to='services.upholsterymaterialtypes'),
        ),
    ]
