# Generated by Django 4.2.17 on 2025-05-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0002_upholsterycarmodels_upholsterymaterialtypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upholsterymaterial',
            options={'verbose_name': 'Upholstery Material', 'verbose_name_plural': 'Upholstery Materials'},
        ),
        migrations.RemoveField(
            model_name='upholsterymaterial',
            name='available',
        ),
        migrations.RemoveField(
            model_name='upholsterymaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='upholsterymaterial',
            name='durability_rating',
        ),
        migrations.RemoveField(
            model_name='upholsterymaterial',
            name='price_per_seat',
        ),
        migrations.AlterField(
            model_name='upholsterybooking',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_bookings',
                                    to='services.upholsterycarmodels'),
        ),
        migrations.AlterField(
            model_name='upholsterybooking',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_bookings',
                                    to='services.upholsterymaterialtypes'),
        ),
        migrations.AlterField(
            model_name='upholsterybooking',
            name='primary_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_bookings',
                                    to='services.upholsterymaterial'),
        ),
    ]
