# Generated by Django 4.2.17 on 2025-05-23 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_upholsterymaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=200, verbose_name='الماركة والطراز')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900),
                                                         django.core.validators.MaxValueValidator(2030)],
                                             verbose_name='سنة الصنع')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)],
                                                verbose_name='عدد الكيلومترات')),
                ('fuel_type', models.CharField(
                    choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهربائي'), ('hybrid', 'هايبرد')],
                    max_length=20, verbose_name='نوع الوقود')),
                ('transmission',
                 models.CharField(choices=[('automatic', 'أوتوماتيك'), ('manual', 'يدوي')], max_length=20,
                                  verbose_name='ناقل الحركة')),
                ('color', models.CharField(max_length=100, verbose_name='لون السيارة')),
                ('previous_accidents', models.BooleanField(verbose_name='حوادث سابقة')),
                ('previous_owners_count', models.IntegerField(
                    choices=[(1, 'مالك واحد'), (2, 'مالكين'), (3, 'ثلاثة ملاك'), (4, 'أربعة ملاك أو أكثر')],
                    verbose_name='عدد الملاك السابقين')),
                ('body_condition', models.CharField(
                    choices=[('excellent', 'ممتازة'), ('good', 'جيدة'), ('needs_maintenance', 'تحتاج صيانة')],
                    max_length=20, verbose_name='حالة الهيكل')),
                ('accessories', models.TextField(blank=True, help_text='قائمة الملحقات مفصولة بفواصل', null=True,
                                                 verbose_name='الملحقات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10,
                                              validators=[django.core.validators.MinValueValidator(0)],
                                              verbose_name='السعر المطلوب')),
                ('seller_name', models.CharField(max_length=200, verbose_name='اسم البائع')),
                ('seller_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('seller_email',
                 models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('status', models.CharField(
                    choices=[('draft', 'مسودة'), ('active', 'نشط'), ('sold', 'مباع'), ('inactive', 'غير نشط')],
                    default='draft', max_length=20, verbose_name='حالة الإعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/%Y/%m/%d/', verbose_name='صورة السيارة')),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                                  to='services.carlisting')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
            },
        ),
    ]
