# Generated by Django 4.2.17 on 2025-05-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0004_carlisting_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upholsterycarmodels',
            name='upholstery_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_models',
                                    to='services.upholsterymaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upholsterymaterial',
            name='price',
            field=models.DecimalField(decimal_places=3, default=240, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='upholsterymaterialtypes',
            name='upholstery_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='material_types', to='services.upholsterymaterial'),
            preserve_default=False,
        ),
    ]
