# Generated by Django 4.2.17 on 2025-05-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0005_upholsterycarmodels_upholstery_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upholsterymaterialtypes',
            name='upholstery_car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='material_types', to='services.upholsterycarmodels'),
            preserve_default=False,
        ),
    ]
