# Generated by Django 4.2.17 on 2025-05-31 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_remove_vehicle_condition_ar_remove_vehicle_for_rent_and_more'),
        ('services', '0006_upholsterymaterialtypes_upholstery_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons',
                                           to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(blank=True, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Comparison',
                'verbose_name_plural': 'Vehicle Comparisons',
            },
        ),
    ]
