# Generated by Django 4.2.17 on 2025-06-01 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0007_vehiclecomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecomparison',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
